
##docker run --privileged -e API_URL={API_IP}:80 -e ROOM_NAME=luna mcopjan/raspberry-hum-temp-agent:latest

FROM python:3.8-alpine
WORKDIR app

ENV API_URL=localhost:5555
ENV SENSOR_MODEL=11
ENV GPIO_PIN=17
ENV ROOM_NAME=demo
ENV INTERVAL_SEC=60

COPY ./get-humidity-temperature.py .
COPY ./healthcheck.py .
RUN apk update && apk add bash && apk add --no-cache git && apk add python3-dev \
                        gcc \
                        libc-dev

RUN pip3 install requests                        
                            
RUN git clone https://github.com/adafruit/Adafruit_Python_DHT.git                                             
RUN cd ./Adafruit_Python_DHT && python3 setup.py install

ENTRYPOINT python3 get-humidity-temperature.py $API_URL $SENSOR_MODEL $GPIO_PIN $ROOM_NAME $INTERVAL_SEC
