#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /src
COPY ["Raspberry.Temperature.Humidity.Api/Raspberry.Temperature.Humidity.Api.csproj", "Raspberry.Temperature.Humidity.Api/"]
RUN dotnet restore "Raspberry.Temperature.Humidity.Api/Raspberry.Temperature.Humidity.Api.csproj"
COPY . .
WORKDIR "/src/Raspberry.Temperature.Humidity.Api"
RUN dotnet build "Raspberry.Temperature.Humidity.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Raspberry.Temperature.Humidity.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Raspberry.Temperature.Humidity.Api.dll"]