name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Raspberry Agent Docker image
      run: docker build . --file Dockerfile_Raspberry_Agent --tag mcopjan/raspberry-hum-temp-agent:latest
      
    - uses: actions/checkout@v3
    - name: Build the Api Docker image
      run: docker buildx build --platform linux/amd64,linux/arm/v7 . --file Dockerfile_Api --tag mcopjan/raspberry-hum-temp-api:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push the Agent Docker Image
      run: docker push mcopjan/raspberry-hum-temp-agent:latest
      
    - name: Push the Api Docker Image
      run: docker push mcopjan/raspberry-hum-temp-api:latest
