name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted
    
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - uses: actions/checkout@v3
    - name: Build & Push Agent Docker image
      run: docker buildx build --file Dockerfile_Raspberry_Agent --platform linux/arm/v6,linux/arm/v7 -t mcopjan/raspberry-hum-temp-agent:latest -t mcopjan/raspberry-hum-temp-agent:$env:GITHUB_RUN_NUMBER --push .
      
    - uses: actions/checkout@v3
    - name: Build the Api Docker image
      run: docker build . --file Dockerfile_Api --tag mcopjan/raspberry-hum-temp-api:latest

    - name: Push the Api Docker Image
      run: docker push mcopjan/raspberry-hum-temp-api:latest
