name: Build and Push Api docker image

on:
  push:
    branches: [ "master" ]
    paths:
      - 'RaspberryTemperatureHumidityApi/**'
      - 'Dockerfile_Api'
      - '.github/workflows/docker-publish-api.yml'
  workflow_dispatch:  

jobs:

  build:

    runs-on: self-hosted
    
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v3
    - name: Build the Api Docker image
      run: docker build . --file Dockerfile_Api -t mcopjan/raspberry-hum-temp-api:latest -t mcopjan/raspberry-hum-temp-api:${{github.run_number}}

    - name: Push the Api Docker Image
      run: docker push mcopjan/raspberry-hum-temp-api:latest

    - name: Push the Api Docker Image
      run: docker push mcopjan/raspberry-hum-temp-api:${{github.run_number}} 
