name: Build and Push Agent docker image

on:
  push:
    branches: [ "master" ]
    paths:
      - 'get-humidity-temperature.py'
      - 'Dockerfile_Raspberry_Agent'
    

jobs:

  build:

    runs-on: self-hosted
    
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - uses: actions/checkout@v3
    - name: Build & Push Agent Docker image
      run: docker buildx build --file Dockerfile_Raspberry_Agent --platform linux/arm/v6,linux/arm/v7 -t mcopjan/raspberry-hum-temp-agent:latest -t mcopjan/raspberry-hum-temp-agent:${{github.run_number}} --push .
