name: Build and Push Api docker image

on:
  push:
    branches: [ "master" ]
    paths:
      - 'RaspberryTemperatureHumidityApi/**'
      - 'Dockerfile_Api'
    

jobs:

  build:

    runs-on: self-hosted
    
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v3
    - name: Build & Push API Docker image
      run: docker buildx build --file Dockerfile_Api --platform linux/arm/v6,linux/arm/v7 -t mcopjan/raspberry-hum-temp-api:latest -t mcopjan/raspberry-hum-temp-api:${{github.run_number}} --push .
